apache:
  build: ./docker/apache
  volumes:
    - "./src/:/var/www/html"
  links:
    - mysql
  ports:
    - "8080:80"
mysql:
  build: ./docker/mysql
  volumes:
    - "./docker/mysql:/docker-entrypoint-initdb.d"
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: myPassword
    MYSQL_DATABASE: blog
    MYSQL_USER: userBlog
    MYSQL_PASSWORD: passBlog